### Register User

POST http://127.0.0.1:8000/api/auth/register/
Content-Type: application/json

{
    "username": "johndoe3",
    "password": "securepassword123",
    "first_name": "John",
    "last_name": "Doe",
    "email": "ddonierov@gmail.com"
}

### Login User

POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "username": "johndoe3",
    "password": "securepassword123"
}

### Refresh Token User

POST http://localhost:8000/api/auth/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2Njc2NTAxMiwiaWF0IjoxNzY2MTYwMjEyLCJqdGkiOiIzZTg2OGZkMDAxOTc0ZjNiODk5ZTY1YzhlMjg2MzJkZSIsInVzZXJfaWQiOiIyIn0.aqGmaaA4ooPNvAc8SXBOGUvxTVbs1gkHhmRi6A-4ugs"
}


### Get all projects 

GET http://localhost:8000/api/project/all
Content-Type: application/json

### Create project
POST http://localhost:8000/api/project/all/
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MjQ2NjEyLCJpYXQiOjE3NjYxNjAyMTIsImp0aSI6IjA0M2RlMWZhYzQzYzRkMGRhNTJhOGE0NzhjMGMyM2I3IiwidXNlcl9pZCI6IjIifQ.2_0y9-wpdpQssAgujv1Wfi0WKH1PPaxtT5LhblPbFos

{
    "name": "Test",
    "owner": 1,
    "members": []
}