# Generated by Django 5.2.7 on 2025-12-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_todo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
