# Generated by Django 5.2.7 on 2026-01-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_owner_remove_todo_assigned_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
